# HCAII Experiment Data
to get an Idea about the datastructure to set up the guacamol data for training a model

In [48]:
# load .pkl file
import pickle

with open('/Volumes/PHILIPS/coati/0.pkl', 'rb') as f:
    data = pickle.load(f)

In [50]:
print(type(data))
print(data[0])


<class 'list'>
{'smiles': 'Cc1cn2c(n1)[C@@H](C(=O)NCCCN(C(=O)c1nc(O)sc1C)C1CC1)CCC2', 'zinc_id': 'ZINCtt000007JAXK', 'standardized_smiles': 'Cc1cn2c(n1)[C@@H](C(=O)NCCCN(C(=O)c1nc(O)sc1C)C1CC1)CCC2', 'atoms': array([ 6,  6,  6,  7,  6,  7,  6,  6,  8,  7,  6,  6,  6,  7,  6,  8,  6,
        7,  6,  8, 16,  6,  6,  6,  6,  6,  6,  6,  6,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1], dtype=uint8), 'adj_mat': array([[ 0. ,  1. ,  1. ],
       [ 1. ,  2. ,  1.5],
       [ 2. ,  3. ,  1.5],
       [ 3. ,  4. ,  1.5],
       [ 4. ,  5. ,  1.5],
       [ 4. ,  6. ,  1. ],
       [ 6. ,  7. ,  1. ],
       [ 7. ,  8. ,  2. ],
       [ 7. ,  9. ,  1. ],
       [ 9. , 10. ,  1. ],
       [10. , 11. ,  1. ],
       [11. , 12. ,  1. ],
       [12. , 13. ,  1. ],
       [13. , 14. ,  1. ],
       [14. , 15. ,  2. ],
       [14. , 16. ,  1. ],
       [16. , 17. ,  1.5],
       [17. , 18. ,  1.5],
       [18. , 19. ,  1. ],


In [9]:
print(hcaii['coords'][0])
print(type(hcaii['coords'][0]))

[[-2.6437  2.6558  1.8087]
 [-3.1719  1.7205  0.792 ]
 [-4.325   0.9662  0.8384]
 [-4.3651  0.3059 -0.3525]
 [-3.2542  0.6579 -1.0749]
 [-2.5077  1.5096 -0.3968]
 [-2.9877  0.113  -2.445 ]
 [-1.8478 -0.9089 -2.3673]
 [-1.9592 -2.0689 -2.7583]
 [-0.6625 -0.4029 -1.8735]
 [ 0.5412 -1.1994 -1.7706]
 [ 0.6044 -2.0041 -0.4749]
 [ 0.7004 -1.1392  0.786 ]
 [ 1.9717 -0.4177  0.8937]
 [ 3.1087 -1.1445  1.2958]
 [ 3.0134 -2.2989  1.7181]
 [ 4.4335 -0.4965  1.1907]
 [ 4.728   0.4672  0.2157]
 [ 5.9732  0.8373  0.3338]
 [ 6.4539  1.7505 -0.4865]
 [ 6.8928  0.1014  1.55  ]
 [ 5.5197 -0.8293  1.9976]
 [ 5.609  -1.817   3.1096]
 [ 1.9799  0.9863  0.5599]
 [ 2.3715  2.0323  1.5768]
 [ 0.9562  1.9511  1.1056]
 [-4.2638 -0.4814 -3.067 ]
 [-5.0374 -1.3481 -2.0667]
 [-5.4363 -0.5414 -0.8336]
 [-3.4515  3.2528  2.2437]
 [-1.9173  3.344   1.3661]
 [-2.1509  2.1029  2.614 ]
 [-5.0978  0.8699  1.5883]
 [-2.6367  0.9277 -3.0916]
 [-0.6853  0.5273 -1.4572]
 [ 0.5744 -1.8885 -2.6221]
 [ 1.3953 -0.5238 -1.8672]
 

In [34]:
print

smiles                                                     CCC(C)(C)Br
atoms                [6, 6, 6, 6, 6, 35, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
coords               [[0.77919738, -0.37885212, 0.79409621], [-0.59...
partition                                                        train
source_collection                                             guacamol
Name: 0, dtype: object


# Guacamol Data

In [1]:
# load .csv file
import pickle

with open('/Users/stefanhangler/Documents/Uni/Msc_AI/3_Semester/Seminar_Practical Work/Code.nosync/COATI/examples/train_valid_test_guacamol.pkl', 'rb') as f:
    guacamol = pickle.load(f)


In [3]:
print(type(guacamol))
print(guacamol.iloc[0])

<class 'pandas.core.frame.DataFrame'>
smiles                                                     CCC(C)(C)Br
atoms                [6, 6, 6, 6, 6, 35, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
coords               [[0.77919738, -0.37885212, 0.79409621], [-0.59...
partition                                                        train
source_collection                                             guacamol
Name: 0, dtype: object


In [4]:
import pandas as pd

# Assuming 'df' is your pandas DataFrame
df = pd.read_pickle('/Users/stefanhangler/Documents/Uni/Msc_AI/3_Semester/Seminar_Practical Work/Code.nosync/COATI/examples/train_valid_test_guacamol.pkl')  # Load your DataFrame from a pickle file


In [7]:

import tqdm
# Initialize an empty list to store your dictionaries
list_of_dicts = []

# Iterate over each row in the DataFrame
for index, row in tqdm.tqdm(df.iterrows(), total=len(df)):
    # Construct a dictionary for each row
    entry = {
        'smiles': row['smiles'],
        'atoms': row['atoms'],
        'coords': row['coords'],
        'source_collection': row['source_collection'],
        'partition': row.get('partition'),
    }

    # Append the dictionary to the list
    list_of_dicts.append(entry)

100%|██████████| 1589797/1589797 [02:43<00:00, 9718.95it/s] 


In [8]:
# store list_of_dicts in a pickle file
import pickle

with open('/Users/stefanhangler/Documents/Uni/Msc_AI/3_Semester/Seminar_Practical Work/Code.nosync/COATI/examples/train_valid_test_guacamol_list.pkl', 'wb') as f:
    pickle.dump(list_of_dicts, f)

In [13]:
with open('/Users/stefanhangler/Documents/Uni/Msc_AI/3_Semester/Seminar_Practical Work/Code.nosync/COATI/examples/train_valid_test_guacamol_list.pkl', 'rb') as f:
    data = pickle.load(f)

import pandas as pd

df = pd.DataFrame(data)

# print unique values in column 'partition' and count them
print(df['partition'].value_counts())

train    1271836
test      238466
valid      79495
Name: partition, dtype: int64


In [12]:
import pandas as pd

guacamol_df = pd.DataFrame(data)
print(type(guacamol_df['atoms'][0]))

# check if in first row the value in column partition is train


<class 'numpy.ndarray'>


In [29]:
print(df['atoms'][0])
print(type(df['atoms'][0]))



[ 6  6  6  6  6 35  1  1  1  1  1  1  1  1  1  1  1]
<class 'numpy.ndarray'>


In [30]:
print(df['coords'][0])
print(type(df['coords'][0]))

[[ 0.77919738 -0.37885212  0.79409621]
 [-0.59915176  0.09005053  0.43215675]
 [-1.2439719  -0.79659656 -0.61070348]
 [-0.65889248  1.49995473 -0.0469612 ]
 [-1.69814093 -0.07384639  2.03462616]
 [ 2.25522228 -1.404456   -0.38616722]
 [ 2.57259291  0.32551001 -0.17056892]
 [ 1.2720485  -0.27115557 -1.32946089]
 [ 0.661645   -1.41826167  1.20853113]
 [ 1.204467    0.21590541  1.62506238]
 [-1.05566783 -0.36153166 -1.62369487]
 [-2.33335852 -0.85974912 -0.49246425]
 [-0.75625327 -1.79781899 -0.56980021]
 [-1.71496358  1.84056761  0.02737312]
 [-0.35748139  1.60001995 -1.12210047]]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
import ast
import re

# Function to convert string representation of space-separated numbers to numpy.ndarray
def str_to_ndarray(s):
    # Remove square brackets and split the string by spaces
    s = s.strip('[]')
    return np.array([int(x) for x in s.split()])

# Function to convert string representation of lists of lists with floats
def str_to_ndarray_2d(s):
    # Use regex to find all groups of floats
    s = s.strip('[]')
    groups = re.findall(r'\[([^\]]+)\]', s)
    cleaned_groups = [group.replace('[', '').replace(']', '') for group in groups]
    return np.array([list(map(float, group.split())) for group in cleaned_groups])


# Apply the function to the 'atoms' column
#df['atoms'] = df['atoms'].apply(str_to_ndarray)

# Apply the function to the 'coords' column
df['coords'] = df['coords'].apply(str_to_ndarray_2d)

# Verify the conversion
print(df['atoms'][0])
print(type(df['atoms'][0]))

print(df['coords'][0])
print(type(df['coords'][0]))

[ 6  6  6  6  6 35  1  1  1  1  1  1  1  1  1  1  1]
<class 'numpy.ndarray'>
[[ 0.77919738 -0.37885212  0.79409621]
 [-0.59915176  0.09005053  0.43215675]
 [-1.2439719  -0.79659656 -0.61070348]
 [-0.65889248  1.49995473 -0.0469612 ]
 [-1.69814093 -0.07384639  2.03462616]
 [ 2.25522228 -1.404456   -0.38616722]
 [ 2.57259291  0.32551001 -0.17056892]
 [ 1.2720485  -0.27115557 -1.32946089]
 [ 0.661645   -1.41826167  1.20853113]
 [ 1.204467    0.21590541  1.62506238]
 [-1.05566783 -0.36153166 -1.62369487]
 [-2.33335852 -0.85974912 -0.49246425]
 [-0.75625327 -1.79781899 -0.56980021]
 [-1.71496358  1.84056761  0.02737312]
 [-0.35748139  1.60001995 -1.12210047]]
<class 'numpy.ndarray'>


In [23]:
# safe df as .pkl file and csv file
df.to_pickle('/Users/stefanhangler/Documents/Uni/Msc_AI/3_Semester/Seminar_Practical Work/Code.nosync/COATI/examples/train_valid_test_guacamol.pkl')
df.to_csv('/Users/stefanhangler/Documents/Uni/Msc_AI/3_Semester/Seminar_Practical Work/Code.nosync/COATI/examples/train_valid_test_guacamol.csv', index=False)

In [4]:
def load_dataset_links(file_path: str) -> list:
    """
    Load dataset links from a text file.

    Args:
        file_path (str): Path to the text file containing dataset links.

    Returns:
        list: A list of dataset URLs.
    """
    with open(file_path, 'r') as file:
        links = file.read().splitlines()
    return links

import boto3
import os
import pickle

# def download_from_s3(url: str, local_dir: str):
#     """
#     Download a file from an S3 bucket URL to a local directory.

#     Args:
#         url (str): The S3 URL of the file.
#         local_dir (str): The local directory to save the file.
#     """
#     bucket_name = url.split('/')[2]
#     object_key = '/'.join(url.split('/')[3:])
#     local_path = os.path.join(local_dir, object_key.split('/')[-1])
    
#     s3 = boto3.client('s3')
#     if not os.path.exists(local_dir):
#         os.makedirs(local_dir, exist_ok=True)
#     s3.download_file(Bucket=bucket_name, Key=object_key, Filename=local_path)
#     print(f"Downloaded {object_key} to {local_path}")
#     return local_path

def load_pickle_file(file_path: str):
    """
    Load a pickle file.

    Args:
        file_path (str): Path to the pickle file.

    Returns:
        Any: The content loaded from the pickle file.
    """
    with open(file_path, "rb") as f:
        data = pickle.load(f)
    return data

In [3]:
links_path = 'admet_datasets.txt'
dataset_links = load_dataset_links(links_path)
local_dir = './datasets'

for link in dataset_links:
    print("Processing link:", link)
    local_file_path = download_from_s3(link, local_dir)
    dataset = load_pickle_file(local_file_path)
    print(f"Loaded dataset with keys: {list(dataset[0].keys()) if len(dataset) > 0 else 'Empty dataset'}")

Processing link: s3://terray-public/datasets/ames.pkl


EndpointConnectionError: Could not connect to the endpoint URL: "https://terray-public.s3.Austria.amazonaws.com/datasets/ames.pkl"

In [4]:
import pickle
#from coati.common.s3 import download_from_s3

#download_from_s3("s3://terray-public/datasets/delaney.pkl")

# datasets are available as pickle files (list of dictionaries)
with open("./datasets/clintox.pkl", "rb") as f:
    delaney = pickle.load(f)

# to pandas dataframe
import pandas as pd
df = pd.DataFrame(delaney)
df.head()

# print unique value in df for column 'target'
#df['target'].unique()

target  dataset   Drug_ID  \
0       0  clintox  Drug 663   
1       0  clintox  Drug 275   
2       0  clintox  Drug 396   
3       0  clintox  Drug 219   
4       0  clintox  Drug 923   

                                               atoms  \
0  [6, 6, 6, 16, 6, 7, 6, 8, 8, 1, 1, 1, 1, 1, 1,...   
1  [7, 6, 7, 6, 8, 6, 6, 6, 6, 6, 6, 6, 8, 1, 1, ...   
2  [6, 6, 6, 6, 6, 7, 6, 8, 6, 6, 7, 6, 8, 6, 7, ...   
3  [7, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 8, 7, ...   
4  [6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 6, 6, 6, ...   

                                                Drug partition  Y  \
0                    CC(C)(S)[C@@H]([NH3+])C(=O)[O-]      test  0   
1                        NC1=[NH+]C(=O)C(c2ccccc2)O1      test  0   
2  CC(C)C[C@@H](NC(=O)[C@H](C)NC(=O)CNC(=O)[C@@H]...      test  0   
3                   Nc1cccc2c1CN(C1CCC(=O)NC1=O)C2=O      test  0   
4  Cc1c(C)c2c(c(C)c1O)CCC(C)(COc1ccc(CC3SC(=O)[N-...      test  0   

                                              smiles  \
0                    CC(C)(S)[C@@H]([NH3+])C(=O)[O-]   
1                        NC1=[NH+]C(=O)C(c2ccccc2)O1   
2  CC(C)C[C@@H](NC(=O)[C@H](C)NC(=O)CNC(=O)[C@@H]...   
3                   Nc1cccc2c1CN(C1CCC(=O)NC1=O)C2=O   
4  Cc1c(C)c2c(c(C)c1O)CCC(C)(COc1ccc(CC3SC(=O)[N-...   

                                              coords  \
0  [[-1.1587, 1.501, 0.4467], [-0.5729, 0.086, 0....   
1  [[3.4802, 1.2624, 0.2219], [2.5354, 0.4995, -0...   
2  [[-6.1262, -3.7166, 7.069], [-6.9619, -2.4409,...   
3  [[3.1444, 0.2364, -2.4085], [3.1163, -0.0045, ...   
4  [[-6.5206, 0.6231, 2.6371], [-5.5766, 0.2606, ...   

                                 Barlow Venti (Text)  ...  \
0  [-0.48596588, -0.40367287, -0.32968014, -0.040...  ...   
1  [0.2941416, 0.18029086, -0.22861026, -0.049696...  ...   
2  [-0.12584504, -0.21312052, -0.15873043, -0.420...  ...   
3  [-0.17993519, -0.12503093, -0.10035531, -0.714...  ...   
4  [-0.09498369, 0.3513912, -0.19573663, -0.27671...  ...   

                            Barlow Closed FP (Point)  \
0  [-0.034439653, 0.34682173, 0.5232295, 0.339287...   
1  [-0.037776455, 0.2113951, 1.1339982, 0.2314647...   
2  [0.4703792, 0.124379374, 0.16749996, 0.7778032...   
3  [-0.6833182, 0.026306301, 0.10959904, -0.40253...   
4  [-0.2950976, 1.0571643, -0.057204343, 0.200984...   

                                            RDKit 2D  \
0  [1.0, 0.9952556386838793, 0.003338733333477606...   
1  [1.0, 0.8736604457896888, 0.037759519196055025...   
2  [1.0, 0.005977392609663165, 0.9999999999997586...   
3  [1.0, 0.679323244027271, 0.16051684104770916, ...   
4  [1.0, 0.150942407522209, 0.6028500013673688, 0...   

                                            RDKit FP  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, ...   
2  [1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, ...   
3  [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...   
4  [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, ...   

                                          ECFP6 2048  \
0  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                CDDD  \
0  [-0.9194064, 0.3526249, -0.44385064, -0.948228...   
1  [0.80000734, 0.71778387, 0.64834, -0.3823671, ...   
2  [-0.5920336, -0.28254712, -0.18214382, 1.26347...   
3  [0.495663, 0.04323706, 0.7806182, -0.07695059,...   
4  [0.7904057, 0.5615183, 0.9352038, -0.58156925,...   

                                       ChemBERTa MTR  \
0  [-0.3597712218761444, 0.15387509763240814, -0....   
1  [-0.01589236594736576, -0.07616246491670609, -...   
2  [0.07713872939348221, -0.0604865662753582, -0....   
3  [-0.16631020605564117, -0.0597807802259922, -0...   
4  [-0.2895241677761078, 0.3468022048473358, -0.1...

In [5]:
# iterate over all datasets in './datasets' directory
import os
import pickle
import pandas as pd

for file in os.listdir('./datasets'):
    if file.endswith('.pkl'):
        with open(f'./datasets/{file}', 'rb') as f:
            dataset = pickle.load(f)
            print(f"Loaded dataset {file}")
            # check if dataset has columns
            print(len(dataset))
            # try:
            #     if 'target' in dataset[0].keys():
            #         print(f"unique values in target column: {pd.DataFrame(dataset)['target'].unique()}")
            #     # elif dataset has columns
            #     elif len(dataset) > 0:
            #         print("columns: ", list(dataset[0].keys()))
            # except:
            #     # dataset to dataframe
            #     df = pd.DataFrame(dataset)
            #     print(df.head())

Loaded dataset ames.pkl
7278
Loaded dataset bace_regression.pkl
1513
Loaded dataset cyp3a4_veith.pkl
12328
Loaded dataset bace_classification.pkl
1513
Loaded dataset chembl_canonical_smiles.pkl
2177805
Loaded dataset half_life_obach.pkl
667
Loaded dataset pgp_broccatelli.pkl
1218
Loaded dataset bioavailability_ma.pkl
640
Loaded dataset caco2_wang.pkl
910
Loaded dataset clintox.pkl
1478
Loaded dataset herg_karim.pkl
13445
Loaded dataset clearance_microsome_az.pkl
1102
Loaded dataset clearance_hepatocyte_az.pkl
1213
Loaded dataset hiv.pkl
41127
Loaded dataset dili.pkl
475
Loaded dataset ppbr_az.pkl
2790
Loaded dataset vdss_lombardo.pkl
1130
Loaded dataset hia_hou.pkl
578
Loaded dataset cyp2c9_veith.pkl
12092
Loaded dataset ld50_zhu.pkl
7385
Loaded dataset herg.pkl
655
Loaded dataset delaney.pkl
1128


In [9]:
len(delaney)

1128

In [14]:
links_path = 'admet_datasets.txt'
dataset_links = load_dataset_links(links_path)
local_dir = './datasets'

for link in dataset_links:
    # extract dataset_name from the link
    dataset_name = link.split('/')[-1]
    dataset_path = os.path.join(local_dir, dataset_name)

    # check if the dataset is already downloaded
    if os.path.exists(dataset_path):
        print(f"{dataset_name} already exists")
        continue
    
    try:
        download_from_s3(link)
    except Exception as e:
        print(f"Failed to download {dataset_name}: {e}")
        continue

    with open("./datasets/delaney.pkl", "rb") as f:
        dataset = pickle.load(f)

    print(f'{dataset_name}:\n {dataset[0].keys()}')


ames.pkl already exists
bace_classification.pkl already exists
bace_regression.pkl already exists
bioavailability_ma.pkl already exists
caco2_wang.pkl already exists
chembl_canonical_smiles.pkl already exists
clearance_hepatocyte_az.pkl already exists
clearance_microsome_az.pkl already exists
clintox.pkl already exists
delaney.pkl already exists
dili.pkl already exists
half_life_obach.pkl already exists
herg.pkl already exists
Failed to download herg_inhib.pkl: Could not connect to the endpoint URL: "https://terray-public.s3.us-west-2.amazonaws.com/datasets/herg_inhib.pkl"
File downloaded successfully to ./datasets/herg_karim.pkl
herg_karim.pkl:
 dict_keys(['raw_smiles', 'smiles', 'partition', 'dataset', 'atoms', 'coords', 'target', 'Barlow Venti (Text)', 'Barlow Venti (Point)', 'Grande Open (Text)', 'Grande Open (Point)', 'Tall Closed (Text)', 'Tall Closed (Point)', 'Barlow Closed (Text)', 'Barlow Closed (Point)', 'Grande Closed (Text)', 'Grande Closed (Point)', 'Barlow Closed FP (Tex

In [3]:
from rdkit import Chem

def remove_attachment_point(smiles):
    return smiles.replace('*', '')

# Example Usage
clean_smiles = remove_attachment_point('*C(=O)[C@H](CCCCNC(=O)OCCOC)NC(=O)OCCOC')

def substitute_with_hydrogen(smiles):
    return smiles.replace('*', 'H')

# Example Usage
#hydrogenated_smiles = substitute_with_hydrogen('*C(=O)[C@H](CCCCNC(=O)OCCOC)NC(=O)OCCOC')

from rdkit import Chem

def validate_smiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return Chem.MolToSmiles(mol)  # Converts to canonical SMILES and validates
    else:
        return None

# Example Usage
validated_smiles = validate_smiles('*C(=O)[C@H](CCCCNC(=O)OCCOC)NC(=O)OCCOC')
if validated_smiles:
    print("Valid SMILES:", validated_smiles)
else:
    print("Invalid SMILES after modification")


Valid SMILES: *C(=O)[C@H](CCCCNC(=O)OCCOC)NC(=O)OCCOC


# Linear Probing Results

In [23]:
# load csv data from /results/linear_probing_results.csv
import pandas as pd
results = pd.read_csv("results/linear_probing_results.csv")
results

Dataset  Assay Index        Analysis Type  \
0              bace_c_scaffold_split            0  logistic_regression   
1            bace_c_scaffold_split_0            0  logistic_regression   
2            bace_c_scaffold_split_1            0  logistic_regression   
3            bace_c_scaffold_split_2            0  logistic_regression   
4            bace_c_scaffold_split_3            0  logistic_regression   
...                              ...          ...                  ...   
31583  uspto_rclass_scaffold_split_5            9  logistic_regression   
31584  uspto_rclass_scaffold_split_6            9  logistic_regression   
31585  uspto_rclass_scaffold_split_7            9  logistic_regression   
31586  uspto_rclass_scaffold_split_8            9  logistic_regression   
31587  uspto_rclass_scaffold_split_9            9  logistic_regression   

              Model  AUROC Score  AUROC std      avgp  avgp_std     davgp  \
0      coati_grande     0.798370   0.038282  0.828203  0.045929  0.222940   
1      coati_grande     0.837302   0.033348  0.777878  0.048973  0.360659   
2      coati_grande     0.783632   0.038465  0.783008  0.045552  0.266451   
3      coati_grande     0.879080   0.027555  0.860962  0.038691  0.370896   
4      coati_grande     0.871212   0.029263  0.831655  0.045391  0.414436   
...             ...          ...        ...       ...       ...       ...   
31583         clamp     0.321105   0.013087  0.072603  0.003659 -0.032576   
31584         clamp     0.311779   0.012905  0.066600  0.004036 -0.030980   
31585         clamp     0.308478   0.012120  0.068232  0.003160 -0.033948   
31586         clamp     0.328700   0.012203  0.070524  0.003227 -0.032255   
31587         clamp     0.295592   0.011781  0.064859  0.002990 -0.034121   

       davgp_std  
0       0.044485  
1       0.046143  
2       0.042737  
3       0.046730  
4       0.042302  
...          ...  
31583   0.002343  
31584   0.002720  
31585   0.001969  
31586   0.001825  
31587   0.001773  

[31588 rows x 10 columns]

In [25]:
# print unique values in the 'dataset' column
results['Dataset'].unique()

array(['bace_c_scaffold_split', 'bace_c_scaffold_split_0',
       'bace_c_scaffold_split_1', 'bace_c_scaffold_split_2',
       'bace_c_scaffold_split_3', 'bace_c_scaffold_split_4',
       'bace_c_scaffold_split_5', 'bace_c_scaffold_split_6',
       'bace_c_scaffold_split_7', 'bace_c_scaffold_split_8',
       'bace_c_scaffold_split_9', 'bbbp_scaffold_split',
       'bbbp_scaffold_split_0', 'bbbp_scaffold_split_1',
       'bbbp_scaffold_split_2', 'bbbp_scaffold_split_3',
       'bbbp_scaffold_split_4', 'bbbp_scaffold_split_5',
       'bbbp_scaffold_split_6', 'bbbp_scaffold_split_7',
       'bbbp_scaffold_split_8', 'bbbp_scaffold_split_9',
       'clintox_scaffold_split', 'clintox_scaffold_split_0',
       'clintox_scaffold_split_1', 'clintox_scaffold_split_2',
       'clintox_scaffold_split_3', 'clintox_scaffold_split_4',
       'clintox_scaffold_split_5', 'clintox_scaffold_split_6',
       'clintox_scaffold_split_7', 'clintox_scaffold_split_8',
       'clintox_scaffold_split_9', 'hiv_sc

In [13]:

def extract_base_name(dataset_name):
    return dataset_name.split('_')[0]

# Function to apply the highlighting within each group
def highlight_max(data):
    attr = 'background-color: yellow'
    if data.ndim == 1:  # Series from .apply(axis=0) or axis=1
        is_max = data == data.max()
        return [attr if v else '' for v in is_max]
    else:  # DataFrame from .apply(axis=None)
        is_max = data == data.max().max()
        return pd.DataFrame(np.where(is_max, attr, ''),
                            index=data.index, columns=data.columns)

results['Base Dataset'] = results['Dataset'].apply(extract_base_name)

# Group by the new 'Base Dataset' and 'Model', and then calculate the mean
grouped_df = results.groupby(['Base Dataset', 'Model']).mean(numeric_only=True).reset_index()

# Reset the index if you want 'Base Dataset' and 'Model' back as columns
grouped_df.reset_index(inplace=True)
# Function to apply the highlighting within each group
def highlight_max(data):
    attr = 'background-color: yellow'
    is_max = data == data.max()
    return [attr if v else '' for v in is_max]

# Apply the highlight function for each 'Base Dataset' and save results
styled_dfs = {}
for name, group in grouped_df.groupby('Base Dataset'):
    styled = group.style.apply(highlight_max, subset=['AUROC Score', 'AUROC std', 'avgp', 'avgp_std', 'davgp', 'davgp_std'])
    styled_dfs[name] = styled

# Optionally save each styled DataFrame to HTML
for dataset, styled_df in styled_dfs.items():
    styled_df.to_html(f'{dataset}_highlighted.html')
    print(f"Results for {dataset} saved to {dataset}_highlighted.html")


Results for bace saved to bace_highlighted.html
Results for bbbp saved to bbbp_highlighted.html
Results for clintox saved to clintox_highlighted.html
Results for hiv saved to hiv_highlighted.html
Results for sider saved to sider_highlighted.html
Results for tox21 saved to tox21_highlighted.html
Results for toxcast saved to toxcast_highlighted.html
Results for uspto saved to uspto_highlighted.html


In [15]:
# Assuming you have already created HTML files with styles

# List of HTML files
html_files = [f'{dataset}_highlighted.html' for dataset in styled_dfs.keys()]

# Initialize a variable to hold the combined HTML content
combined_html_content = '<html><head><style>table {width: 100%; border-collapse: collapse;} th, td {border: 1px solid black; padding: 8px; text-align: left;} th {background-color: #f2f2f2;}</style></head><body>'

# Concatenate the content of each styled HTML file
for html_file in html_files:
    with open(html_file, 'r') as file:
        content = file.read()
        # Strip the initial HTML header and body tags to avoid nesting
        content = content.split('<body>')[1].split('</body>')[0].strip()
        combined_html_content += content

combined_html_content += '</body></html>'

# Save the combined HTML content to a new file
with open('combined_highlighted.html', 'w') as file:
    file.write(combined_html_content)

print("Combined HTML with styles saved as 'combined_highlighted.html'")

IndexError: list index out of range

In [26]:
import pandas as pd

# Load the data
df = pd.read_csv('results/linear_probing_results.csv')

# Function to extract the base dataset name
def extract_base_name(dataset_name):
    if 'tox21_10k' in dataset_name:
        return 'tox21_10k'
    
    return dataset_name.split('_')[0]

# Apply the function to the 'Dataset' column
df['Base Dataset'] = df['Dataset'].apply(extract_base_name)

df.drop(columns=['Assay Index'], inplace=True)

# Group by 'Base Dataset' and 'Model', and calculate the mean, ensuring only numeric columns are considered
grouped_df = df.groupby(['Base Dataset', 'Model']).mean(numeric_only=True).reset_index()

# Function to apply the highlighting within each group
def highlight_max(data):
    attr = 'background-color: yellow'
    is_max = data == data.max()
    return [attr if v else '' for v in is_max]

# Combine all HTML contents into one HTML file
html_output = '<html><head><style>table {border-collapse: collapse; width: 100%;} th, td {border: 1px solid black; padding: 8px; text-align: left;}</style></head><body>'

for name, group in grouped_df.groupby('Base Dataset'):
    styled = group.style.apply(highlight_max, subset=['AUROC Score', 'AUROC std', 'avgp', 'avgp_std', 'davgp', 'davgp_std']).render()
    html_output += f'<h1>{name}</h1>{styled}'

html_output += '</body></html>'

# Save the combined HTML to a file
with open('combined_results.html', 'w') as file:
    file.write(html_output)


/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_42555/2940074637.py:31: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score', 'AUROC std', 'avgp', 'avgp_std', 'davgp', 'davgp_std']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_42555/2940074637.py:31: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score', 'AUROC std', 'avgp', 'avgp_std', 'davgp', 'davgp_std']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_42555/2940074637.py:31: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score', 'AUROC std', 'avgp', 'avgp_std', 'davgp', 'davgp_std']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_42555/2940074637.py:31: FutureWarning: this method is deprecated in favour of

In [19]:
# load parquet file

import pandas as pd

# Load the data from a Parquet file
df = pd.read_parquet('3_Semester/Seminar_Practical Work/Code.nosync/COATI/downstream_tasks/data/data/downstream/tox21/compound_names.parquet')

df.head()

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.